# ============================================
# CARDANO COMMUNITY SUITE - MAIN LAUNCHER
# ============================================
# Central entry point for all tools

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Get suite path reliably
if (-not [string]::IsNullOrEmpty($PSScriptRoot)) {
    $SuitePath = $PSScriptRoot
    } elseif (-not [string]::IsNullOrEmpty($MyInvocation.MyCommand.Path)) {
        $SuitePath = Split-Path -Parent $MyInvocation.MyCommand.Path
        } else {
            $SuitePath = Get-Location
            }

            Write-Host "Loading Cardano Community Suite from: $SuitePath" -ForegroundColor Cyan

            function Show-MainMenu {
                # Create main form
                    $form = New-Object System.Windows.Forms.Form
                        $form.Text = "Cardano Community Suite"
                            $form.Size = New-Object System.Drawing.Size(600, 400)
                                $form.StartPosition = "CenterScreen"
                                    $form.BackColor = [System.Drawing.Color]::FromArgb(25, 25, 35)
                                        $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
                                            $form.MaximizeBox = $false
                                                
                                                    # Header
                                                        $labelHeader = New-Object System.Windows.Forms.Label
                                                            $labelHeader.Text = "🔗 Cardano Community Suite"
                                                                $labelHeader.Font = New-Object System.Drawing.Font("Arial", 20, [System.Drawing.FontStyle]::Bold)
                                                                    $labelHeader.ForeColor = [System.Drawing.Color]::Cyan
                                                                        $labelHeader.AutoSize = $true
                                                                            $labelHeader.Location = New-Object System.Drawing.Point(80, 30)
                                                                                
                                                                                    $labelSubtitle = New-Object System.Windows.Forms.Label
                                                                                        $labelSubtitle.Text = "Multi-purpose Cardano toolkit for end-users and admins"
                                                                                            $labelSubtitle.Font = New-Object System.Drawing.Font("Arial", 10)
                                                                                                $labelSubtitle.ForeColor = [System.Drawing.Color]::Gray
                                                                                                    $labelSubtitle.AutoSize = $true
                                                                                                        $labelSubtitle.Location = New-Object System.Drawing.Point(110, 65)
                                                                                                            
                                                                                                                # Buttons
                                                                                                                    $btnEndUser = New-Object System.Windows.Forms.Button
                                                                                                                        $btnEndUser.Text = "👤 End-User Tools"
                                                                                                                            $btnEndUser.Size = New-Object System.Drawing.Size(250, 50)
                                                                                                                                $btnEndUser.Location = New-Object System.Drawing.Point(175, 120)
                                                                                                                                    $btnEndUser.BackColor = [System.Drawing.Color]::FromArgb(50, 120, 180)
                                                                                                                                        $btnEndUser.ForeColor = [System.Drawing.Color]::White
                                                                                                                                            $btnEndUser.Font = New-Object System.Drawing.Font("Arial", 12, [System.Drawing.FontStyle]::Bold)
                                                                                                                                                
                                                                                                                                                    $btnAdmin = New-Object System.Windows.Forms.Button
                                                                                                                                                        $btnAdmin.Text = "👨‍💼 Admin Dashboard"
                                                                                                                                                            $btnAdmin.Size = New-Object System.Drawing.Size(250, 50)
                                                                                                                                                                $btnAdmin.Location = New-Object System.Drawing.Point(175, 190)
                                                                                                                                                                    $btnAdmin.BackColor = [System.Drawing.Color]::FromArgb(180, 140, 50)
                                                                                                                                                                        $btnAdmin.ForeColor = [System.Drawing.Color]::White
                                                                                                                                                                            $btnAdmin.Font = New-Object System.Drawing.Font("Arial", 12, [System.Drawing.FontStyle]::Bold)
                                                                                                                                                                                
                                                                                                                                                                                    $btnDocs = New-Object System.Windows.Forms.Button
                                                                                                                                                                                        $btnDocs.Text = "📖 Documentation"
                                                                                                                                                                                            $btnDocs.Size = New-Object System.Drawing.Size(250, 50)
                                                                                                                                                                                                $btnDocs.Location = New-Object System.Drawing.Point(175, 260)
                                                                                                                                                                                                    $btnDocs.BackColor = [System.Drawing.Color]::FromArgb(100, 100, 100)
                                                                                                                                                                                                        $btnDocs.ForeColor = [System.Drawing.Color]::White
                                                                                                                                                                                                            $btnDocs.Font = New-Object System.Drawing.Font("Arial", 12, [System.Drawing.FontStyle]::Bold)
                                                                                                                                                                                                                
                                                                                                                                                                                                                    # Event handlers
                                                                                                                                                                                                                        $btnEndUser.Add_Click({
                                                                                                                                                                                                                                $form.Hide()
                                                                                                                                                                                                                                        Push-Location $SuitePath
                                                                                                                                                                                                                                                . ".\end-user-app\EndUserGUI.ps1"
                                                                                                                                                                                                                                                        Show-EndUserGUI
                                                                                                                                                                                                                                                                Pop-Location
                                                                                                                                                                                                                                                                        $form.Show()
                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    $btnAdmin.Add_Click({
                                                                                                                                                                                                                                                                                            $form.Hide()
                                                                                                                                                                                                                                                                                                    Push-Location $SuitePath
                                                                                                                                                                                                                                                                                                            . ".\community-admin\AdminGUI.ps1"
                                                                                                                                                                                                                                                                                                                    Show-AdminGUI
                                                                                                                                                                                                                                                                                                                            Pop-Location
                                                                                                                                                                                                                                                                                                                                    $form.Show()
                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                $btnDocs.Add_Click({
                                                                                                                                                                                                                                                                                                                                                        $output = @"
                                                                                                                                                                                                                                                                                                                                                        === CARDANO COMMUNITY SUITE DOCUMENTATION ===

                                                                                                                                                                                                                                                                                                                                                        1. END-USER TOOLS
                                                                                                                                                                                                                                                                                                                                                           - Generate Cardano keypairs
                                                                                                                                                                                                                                                                                                                                                              - Sign messages offline
                                                                                                                                                                                                                                                                                                                                                                 - Export wallet data
                                                                                                                                                                                                                                                                                                                                                                    - Verify signatures locally

                                                                                                                                                                                                                                                                                                                                                                    2. ADMIN DASHBOARD
                                                                                                                                                                                                                                                                                                                                                                       - Generate signing challenges
                                                                                                                                                                                                                                                                                                                                                                          - Verify user signatures
                                                                                                                                                                                                                                                                                                                                                                             - Check on-chain stake
                                                                                                                                                                                                                                                                                                                                                                                - Manage user registry
                                                                                                                                                                                                                                                                                                                                                                                   - Export reports

                                                                                                                                                                                                                                                                                                                                                                                   3. SECURITY FEATURES
                                                                                                                                                                                                                                                                                                                                                                                      - Offline signing (no private keys transmitted)
                                                                                                                                                                                                                                                                                                                                                                                         - Challenge-response authentication
                                                                                                                                                                                                                                                                                                                                                                                            - Ed25519 signature verification
                                                                                                                                                                                                                                                                                                                                                                                               - On-chain stake verification

                                                                                                                                                                                                                                                                                                                                                                                               For full documentation, see: cardano-community-suite\docs\
                                                                                                                                                                                                                                                                                                                                                                                               "@
                                                                                                                                                                                                                                                                                                                                                                                                       [System.Windows.Forms.MessageBox]::Show($output, "Documentation", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
                                                                                                                                                                                                                                                                                                                                                                                                           })
                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                   $form.Controls.Add($labelHeader)
                                                                                                                                                                                                                                                                                                                                                                                                                       $form.Controls.Add($labelSubtitle)
                                                                                                                                                                                                                                                                                                                                                                                                                           $form.Controls.Add($btnEndUser)
                                                                                                                                                                                                                                                                                                                                                                                                                               $form.Controls.Add($btnAdmin)
                                                                                                                                                                                                                                                                                                                                                                                                                                   $form.Controls.Add($btnDocs)
                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                           $form.ShowDialog()
                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                           # Launch
                                                                                                                                                                                                                                                                                                                                                                                                                                           Show-MainMenu
                                                                                                                                                                                                                                                                                                                                                                                                                                           